# fasta; fai
genome:
  fasta:
    path: ref_data/genome/GRCh38
    type: folder
    compressed_checksum: fd041c73877a6a10f5a17e2dcaf6d194
    url: https://downloads.pacbcloud.com/public/reference-genomes/human_GRCh38_no_alt_analysis_set.tar.2023-12-04.gz

bcftools_annotate:
  annotation_db:
    checksum: 4c75c1755a45c64e8af7784db7fde009
    path: ref_data/annotation_db/small_exac_common_3.hg38.vcf.gz
    type: file
    url: https://storage.googleapis.com/gatk-best-practices/somatic-hg38/small_exac_common_3.hg38.vcf.gz
  annotation_db_tbi:
    checksum: f650d1dda6bd68cba65d77f131147985
    path: ref_data/annotation_db/small_exac_common_3.hg38.vcf.gz.tbi
    type: file
    url: https://storage.googleapis.com/gatk-best-practices/somatic-hg38/small_exac_common_3.hg38.vcf.gz.tbi

gatk:
  snp_interval:
    checksum: 32f3be3365e485092c33e9f0997968c1
    path: ref_data/GNOMAD/gnomad_SNP_0.001_target.annotated.hg38.interval_list
    type: file
    url: https://raw.githubusercontent.com/genomic-medicine-sweden/Twist_Solid_pipeline_files/refs/tags/v.0.20.0/cnv/gnomad_SNP_0.001_target.annotated.hg38.interval_list

vep_cache:
  compressed_checksum: bcb3bd066ca9c8c85c811dd5f703e547
  path: ref_data/vep_cache/homo_sapiens_merged_vep_111_GRCh38
  type: folder
  url: ftp://ftp.ensembl.org/pub/release-111/variation/vep/homo_sapiens_merged_vep_111_GRCh38.tar.gz

mappability:
  checksum: c8c77c7cbb5713626389334031e66849
  path: ref_data/mappability/access-10kb.hg38.bed
  type: file
  url: https://raw.githubusercontent.com/etal/cnvkit/52f367bd0edbf55cabaaa2fbcf68c8742dc97b4c/data/access-10kb.hg38.bed

# Local files
# design_bed; design_intervals; design_intervals_gatk_cnv
design:
  gene_panel:
    checksum: da80fd04cb75b7efc8c8bd69c3902d09
    path: ref_data/design/design_files/gene_panel.bed
    type: file
    url: file:/clinical/dev/cgg-cancer/poppy/design_files/Lund_hem-gene-panel-myeloid_v1p2_TE-99236228_hg38_2/Probes_merged_ok_combined_Lund_hem-gene-panel-myeloid_v1p2_TE-99236228_hg38.bed
  gene_panel_interval:
    checksum: f9d511b139c89bc75a5dc64e1ebc2f48
    path: ref_data/design/design_files/gene_panel.interval_list
    type: file
    url: file:/clinical/dev/cgg-cancer/poppy/design_files/Lund_hem-gene-panel-myeloid_v1p2_TE-99236228_hg38_2/Probes_merged_ok_combined_Lund_hem-gene-panel-myeloid_v1p2_TE-99236228_hg38.interval_list

pindel_call:
  include_bed:
    checksum: eb847dae6f3a99f245ea7b95dfc8cfce
    path: ref_data/pindel/genes_pindel.bed
    type: file
    url: file:/clinical/dev/cgg-cancer/poppy/genes_pindel.bed
