# vim: syntax=python tabstop=4 expandtab
# coding: utf-8

__author__ = "Arielle R Munters"
__copyright__ = "Copyright 2022, Arielle R Munters"
__email__ = "arielle.munters@scilifelab.uu.se"
__license__ = "GPL-3"

ruleorder: alignment_samtools_index  > copy_bai

include: "rules/common.smk"
include: "rules/result_files.smk"

report: "report/workflow.rst"


rule all:
    input:
        unpack(compile_output_list),

module prealignment:
    snakefile:
        github(
            "hydra-genetics/prealignment",
            path="workflow/Snakefile",
            tag="v0.1.0",
        )
    config: config

use rule * from prealignment as prealignment_*


module alignment:
   snakefile: github("hydra-genetics/alignment", path="workflow/Snakefile", tag="develop")
   config: config

use rule * from alignment as alignment_*


module qc:
    snakefile: github("hydra-genetics/qc", path="workflow/Snakefile", tag="develop")
    config: config

use rule * from qc as qc_*


module snv_indels:
    snakefile: github("hydra-genetics/snv_indels", path="workflow/Snakefile", tag="develop")
    config: config

##  Fix to save individual callers vcf as well!
##  Filtrera mutect2 before ensemble? Why? Why not?
use rule * from snv_indels as snv_indels_*
