site_name: Twist DNA Hematology
nav:
  - Overview:
    - Introduction: intro.md
    - Overview: overview.md
    - Results files: results_file.md
  - Pipeline:
    - Prealignment: prealignment.md 
    - Alignment: alignment.md
    - SNV_indels: snv_indels.md
    - CNV_SV: cnv_sv.md
    - QC: qc.md
  - Pipeline specific rules:
    - Software: software.md
  - Reference Pipeline:
    - Overview: reference_overview.md
    - Set up and running: reference_setup.md

theme: readthedocs
extra_css: [extra.css]
markdown_extensions:
  - abbr
  - attr_list
  - pymdownx.details
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
      base_path: ["docs/", "workflow/rules/"]
      url_download: "True"
  - mdx_spanner
  - admonition
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

plugins:
  - yaml-schema:
      yaml_files:
        - file: "workflow/schemas/config.schema.yaml"
          tag: "CONFIGSCHEMA"
        - file: "workflow/schemas/resources.schema.yaml"
          tag: "RESOURCESSCHEMA"
  - snakemake-rule:
      rule_folders:
        - 'workflow/rules'
      schemas:
        - 'workflow/schemas/rules.schema.yaml'
