site_name: Poppy
nav:
  - Overview:
      - Introduction: intro.md
      - Pipeline overview: overview.md
      - Output: output_files.md
      - Setup and configuration: setup.md
  - Running Poppy:
      - Poppy: poppy.md
      - Reference pipeline: reference_files.md
  - Step-by-step:
      - Pre-alignment: prealignment.md
      - Alignment: alignment.md
      - SNV and indels: snvs.md
      - CNVs: cnvs.md
      - QC: qc.md
  - Pipeline specific rules:
      - Software: softwares.md
  - Project info:
      - Changelog: changelog.md

theme: readthedocs
extra_css: [extra.css]
markdown_extensions:
  - abbr
  - attr_list
  - pymdownx.details
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
      base_path: ["docs/", "workflow/rules/"]
      url_download: "True"
  # - mdx_spanner
  - admonition
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.blocks.details

plugins:
  - search
  - include-markdown
  - yaml-schema:
      yaml_files:
        - file: "workflow/schemas/config.schema.yaml"
          tag: "CONFIGSCHEMA"
        - file: "workflow/schemas/resources.schema.yaml"
          tag: "RESOURCESSCHEMA"
  - snakemake-rule:
      rule_folders:
        - "workflow/rules"
      schemas:
        - "workflow/schemas/rules.schema.yaml"
  - mkdocs-simple-hooks:
      hooks:
        on_pre_build: "docs.hooks:copy_changelog_and_license"
