#/path/to/singularity_cache Adjust as needed
jobs: 100
cores: 20
drmaa: "  -V -cwd -q {resources.queue} -pe mpi {resources.threads} -l excl=1 -o logs/{rule}.stdout -e logs/{rule}.stderr"
printshellcmds: True
use-singularity: True
singularity-prefix: "/clinical/dev/cgg-cancer/poppy/singularity_cache/"
singularity-args: "-e --bind /seqstore --bind /medstore --bind /clinical"
rerun-incomplete: True
restart-times: 1
latency-wait: 180
jobname: "hydra.{name}.{jobid}"
default-resources: [queue="development.q", threads=20] # other resources
