vep_info_fields:
  - Allele
  - Consequence
  - IMPACT
  - SYMBOL
  - Gene
  - Feature_type
  - Feature
  - BIOTYPE
  - EXON
  - INTRON
  - HGVSc
  - HGVSp
  - cDNA_position
  - CDS_position
  - Protein_position
  - Amino_acids
  - Codons
  - Existing_variation
  - DISTANCE
  - STRAND
  - FLAGS
  - VARIANT_CLASS
  - SYMBOL_SOURCE
  - HGNC_ID
  - CANONICAL
  - MANE
  - MANE_SELECT
  - MANE_PLUS_CLINICAL
  - TSL
  - APPRIS
  - CCDS
  - ENSP
  - SWISSPROT
  - TREMBL
  - UNIPARC
  - UNIPROT_ISOFORM
  - REFSEQ_MATCH
  - SOURCE
  - REFSEQ_OFFSET
  - GIVEN_REF
  - USED_REF
  - BAM_EDIT
  - GENE_PHENO
  - SIFT
  - PolyPhen
  - DOMAINS
  - miRNA
  - HGVS_OFFSET
  - AF
  - AFR_AF
  - AMR_AF
  - EAS_AF
  - EUR_AF
  - SAS_AF
  - gnomADe_AF
  - gnomADe_AFR_AF
  - gnomADe_AMR_AF
  - gnomADe_ASJ_AF
  - gnomADe_EAS_AF
  - gnomADe_FIN_AF
  - gnomADe_MID_AF
  - gnomADe_NFE_AF
  - gnomADe_REMAINING_AF
  - gnomADe_SAS_AF
  - gnomADg_AF
  - gnomADg_AFR_AF
  - gnomADg_AMI_AF
  - gnomADg_AMR_AF
  - gnomADg_ASJ_AF
  - gnomADg_EAS_AF
  - gnomADg_FIN_AF
  - gnomADg_MID_AF
  - gnomADg_NFE_AF
  - gnomADg_REMAINING_AF
  - gnomADg_SAS_AF
  - MAX_AF
  - MAX_AF_POPS
  - CLIN_SIG
  - SOMATIC
  - PHENO
  - PUBMED
  - MOTIF_NAME
  - MOTIF_POS
  - HIGH_INF_POS
  - MOTIF_SCORE_CHANGE
  - TRANSCRIPTION_FACTORS

format_fields:
  - GT
  - GQ
  - DP
  - AD
  - VAF
  - PS

columns_keep_snv:
  - CHROM
  - POS
  - REF
  - ALT
  - FILTER
  - CALLER
  - Consequence
  - IMPACT
  - SYMBOL
  - HGVSc
  - HGVSp
  - Existing_variation
  - CLIN_SIG
  - MAX_AF
  - GT
  - GQ
  - DP
  - AD
  - VAF

snvs_remove:
  - intron_variant
  - upstream_gene_variant
  - downstream_gene_variant
  - synonymous_variant

columns_drop_tn: []
columns_drop_sv: []
sv_min_len: 1000
sv_col_max_widths: {}
