filters:
  vaf:
    description: "Soft filter variants with low vaf (AF lower than 0.01)"
    expression: "(INFO:AF:0 < 0.01)"
    soft_filter_flag: "AF_0.01"
    soft_filter: "False"
  depth:
    description: "Soft filter on depth lower than 100"
    expression: "FORMAT:DP < 100"
    soft_filter_flag: "DP_100"
    soft_filter: "True"
  ad:
    description: "Soft filter variants with few observations (AD lower than 5)"
    expression: "(FORMAT:AD:1 < 5)"
    soft_filter_flag: "AD_5"
    soft_filter: "True"
  intron:
    description: "Soft filter intronic variants except if also splice"
    expression: "(exist[intron_variant, VEP:Consequence] and !exist[splice, VEP:Consequence])"
    soft_filter_flag: "Intron"
    soft_filter: "True"
  consequences:
    description: "Soft filter based on consequences"
    expression: "(exist[intergenic_variant, VEP:Consequence] or exist[NMD_transcript_variant, VEP:Consequence] or
                  exist[non_coding_transcript_variant, VEP:Consequence] or
                  exist[upstream_gene_variant, VEP:Consequence] or
                  exist[downstream_gene_variant, VEP:Consequence] or
                  exist[TFBS_ablation, VEP:Consequence] or
                  exist[TFBS_amplification, VEP:Consequence] or
                  exist[TF_binding_site_variant, VEP:Consequence] or
                  exist[regulatory_region_ablation, VEP:Consequence] or
                  exist[regulatory_region_amplification, VEP:Consequence] or
                  exist[regulatory_region_variant, VEP:Consequence])"
    soft_filter_flag: "Consequence"
    soft_filter: "True"
  germline:
    description: "Soft filter germline if >2% in any population from 1000 genomes, ESP or gnomADe"
    expression: "(VEP:MAX_AF > 0.02)"
    soft_filter_flag: "PopAF_0.02"
    soft_filter: "True"
  protein_coding:
    description: "Soft filter variants not deemed protein_coding"
    expression: (VEP:BIOTYPE != protein_coding)
    soft_filter_flag: "Biotype"
    soft_filter: "True"
  artifacts:
    description: "Soft filter position that occurs in 4 or more normal samples (100 %) and AF is less than 5 sd from median af in normalpool"
    expression: "((INFO:Artifact:0 > 3 and INFO:ArtifactNrSD:0 < 5) or (INFO:Artifact:1 > 3 and INFO:ArtifactNrSD:1 < 5))"
    soft_filter_flag: "Artifact"
    soft_filter: "True"
