filters:
  artifacts:
    description: >
      Hard filter variants found in more than 15% of the normal samples
      that are shorter than 10 Mbp
    expression: "(INFO:Twist_AF > 0.15 and INFO:SVLEN < 10000000)"
    soft_filter: false
  copy_number:
    description: >
      Hard filter CNVs with more than 1.4 copies if the BAF is close to
      0.5, as well as all amplifications
    expression: "(INFO:CORR_CN > 1.4 and INFO:BAF > 0.3 and INFO:BAF < 0.7) or (INFO:CORR_CN > 2.5)"
    soft_filter: false
  loh_gene:
    description: "Only keep variants with gene annotations"
    expression: "(!exist[[A-Za-z0-9_,-]+, INFO:Genes])"
    soft_filter: false
