samples: samples_references.tsv
units: units_references.tsv
resources: config/resources_references.yaml

default_container: docker://hydragenetics/common:0.1.9

reference:
  fasta: "/home/nima18/twist-hematology-reference-testenv/hg19/hg19.with.mt.fasta"
  design_bed: "/storage/userdata/references/homo_sapiens/hg19/hydra-genetics/twist-hematology-dna/bed/all_targets_covered_twist_myeloid_v2_hg19_sorted_merge_padded10_annot.bed"
  dict: /home/nima18/twist-hematology-reference-testenv/hg19/hg19.with.mt.dict
  mappability: "/storage/userdata/references/homo_sapiens/hg19/hydra-genetics/twist-solid-dna/bed/access-5k-mappable.hg19.bed"

bed_to_interval_list:
  container: docker://hydragenetics/gatk4:4.2.2.0

cnvkit_build_normal_reference:
  container: docker://hydragenetics/cnvkit:0.9.9

cnvkit_create_targets:
  container: docker://hydragenetics/cnvkit:0.9.9

cnvkit_create_anti_targets:
  container: docker://hydragenetics/cnvkit:0.9.9

collect_read_counts:
  container: docker://hydragenetics/gatk4:4.2.2.0

create_read_count_panel_of_normals:
  container: docker://hydragenetics/gatk4:4.2.2.0

preprocess_intervals:
  container: docker://hydragenetics/gatk4:4.2.2.0

svdb_build:
  container: docker://hydragenetics/svdb:2.6.0

svdb_export:
  container: docker://hydragenetics/svdb:2.6.0
