directory: ./results
files:
  - name: Alignment BAM file
    input: alignment/samtools_merge_bam/{sample}_{type}.bam
    output: bam/{sample}_{type}.bam

  - name: Alignment BAM file index
    input: null
    output: bam/{sample}_{type}.bam.bai

  - name: MultiQC
    input: qc/multiqc/multiqc_DNA.html
    output: qc/multiqc_DNA.html

  - name: SNV ensemble VCF file
    input: snv_indels/bcbio_variation_recall_ensemble/{sample}_{type}.ensembled.vcf.gz
    output: vcf/{sample}_{type}.ensembled.vcf.gz

  - name: Caller-specific VCF file
    input: snv_indels/{caller}/{sample}_{type}.merged.vcf.gz
    output: vcf/{sample}_{type}.{caller}.vcf.gz

  - name: Pindel VCF file
    input: cnv_sv/pindel_vcf/{sample}_{type}.no_contig.vcf.gz
    output: vcf/{sample}_{type}.pindel.vcf.gz

  - name: cnvkit vcf file
    input: cnv_sv/cnvkit_vcf/{sample}_{type}.pathology.vcf
    output: cnv/{sample}_{type}.pathology.cnvkit.vcf
