directory: ./results
files:
  - name: Alignment BAM file
    input: alignment/samtools_merge_bam/{sample}_{type}.bam
    output: bam/{sample}_{type}.bam

  - name: Alignment BAM file index
    input: null
    output: bam/{sample}_{type}.bam.bai

  - name: MultiQC
    input: qc/multiqc/multiqc_DNA.html
    output: qc/multiqc_DNA.html

  - name: SNV ensemble VCF file
    input: snv_indels/bcbio_variation_recall_ensemble/{sample}_{type}.ensembled.vep_annotated.vcf.gz
    output: vcf/{sample}_{type}.ensembled.vep_annotated.vcf.gz

  - name: SNV ensemble soft filtered VCF file
    input: snv_indels/bcbio_variation_recall_ensemble/{sample}_{type}.ensembled.vep_annotated.filter.somatic.vcf.gz
    output: vcf/{sample}_{type}.filter.somatic.vcf.gz

  - name: Caller-specific VCF file
    input: snv_indels/{caller}/{sample}_{type}.merged.vcf.gz
    output: vcf/{sample}_{type}.{caller}.vcf.gz

  - name: Pindel VCF file
    input: cnv_sv/pindel_vcf/{sample}_{type}.no_tc.vep_annotated.vcf.gz
    output: vcf/{sample}_{type}.pindel.vep_annotated.vcf.gz

  - name: SVDB CNV VCF file
    input: cnv_sv/svdb_query/{sample}_{type}.pathology.svdb_query.vcf.gz
    output: cnv/{sample}/{sample}_{type}.pathology.svdb_query.vcf.gz

  - name: CNV HTML report, pathology TC
    input: reports/cnv_html_report/{sample}_{type}.pathology.cnv_report.html
    output: cnv/{sample}/{sample}_{type}.pathology.cnv_report.html

  - name: CNV HTML report, purecn TC
    input: reports/cnv_html_report/{sample}_{type}.purecn.cnv_report.html
    output: cnv/{sample}/{sample}_{type}.purecn.cnv_report.html
