---

default_resources:
  threads: 1
  time: "01:00:00"
  mem_mb: 6144
  mem_per_cpu: 6144
  partition: low

bwa_mem:
  threads: 20
  mem_mb: 122880
  time: "12:00:00"

fastp_pe:
  threads: 5
  mem_mb: 30720

fastqc:
  threads: 10
  mem_mb: 61440
  time: "02:00:00"
  
picard_collect_gc_bias_metrics:
  mem_mb: 30720
  threads: 5
