---

reference:
  fasta: "reference/FLT3.fasta"
  fai: "reference/FLT3.fasta.fai"
  dict: "reference/FLT3.dict"
  design_intervals: "data/bed/design.intervals"
  design_bed: "data/bed/design.bed"

bwa_mem:
  amb: "reference/FLT3.fasta.amb"
  ann: "reference/FLT3.fasta.ann"
  bwt: "reference/FLT3.fasta.bwt"
  pac: "reference/FLT3.fasta.pac"
  sa: "reference/FLT3.fasta.sa"

cnvkit_batch:
  normal_reference: data/cnvkit/cnvkit_pon.cnn

pindel_call:
  include_bed: "data/bed/pindel_regions.bed"
