---
reference:
  fasta: "reference/hg19.fasta"
  fai: "reference/hg19.fasta.fai"
  dict: "reference/hg19.dict"
  design_intervals: "data/bed/design.intervals"
  design_bed: "data/bed/design.bed"
  skip_chrs:
    - "chrM"

bcftools_annotate:
  annotation_db: "reference/small_exac_common_3.hg19.vcf.gz"

bwa_mem:
  amb: "reference/hg19.fasta.amb"
  ann: "reference/hg19.fasta.ann"
  bwt: "reference/hg19.fasta.bwt"
  pac: "reference/hg19.fasta.pac"
  sa: "reference/hg19.fasta.sa"

gatk_collect_allelic_counts:
  SNP_interval: "data/gatk/gnomad_SNP_0.001_target.annotated.interval_list"

merge_cnv_json:
  ref_genes: "reference/refGene.txt"

pindel_call:
  include_bed: "data/bed/pindel_regions.bed"

pindel2vcf:
  refname: "hg19"
  refdate: "2009"

purecn:
  genome: hg19

vep:
  vep_cache: "data/vep_cache"
