$schema: "http://json-schema.org/draft-04/schema#"
description: snakemake configuration file
type: object
properties:

  bed_to_interval_list:
    type: object
    description: >
      config for the bed_to_interval_list rule
    properties:
      container:
        type: string
        description: >
          uri pointing to docker/apptainer image that should be used
        format: uri-reference
    required:
      - container

  cnvkit_build_normal_reference:
    type: object
    description: >
      config for the cnvkit_build_normal_reference rule
    properties:
      container:
        type: string
        description: >
          uri pointing to docker/apptainer image that should be used
        format: uri-reference
    required:
      - container

  cnvkit_create_targets:
    type: object
    description: >
      config for the cnvkit_create_targets rule
    properties:
      container:
        type: string
        description: >
          uri pointing to docker/apptainer image that should be used
        format: uri-reference
    required:
      - container

  collect_read_counts:
    type: object
    description: >
      config for the collect_read_counts rule
    properties:
      container:
        type: string
        description: >
          uri pointing to docker/apptainer image that should be used
        format: uri-reference
    required:
      - container

  create_read_count_panel_of_normals:
    type: object
    description: >
      config for the create_read_count_panel_of_normals rule
    properties:
      container:
        type: string
        description: >
          uri pointing to docker/apptainer image that should be used
        format: uri-reference
    required:
      - container

  default_container:
    type: string
    description: >
      uri pointing to default docker/apptainer image that should be used
    format: uri-reference

  preprocess_intervals:
    type: object
    description: >
      config for the preprocess_intervals rule
    properties:
      container:
        type: string
        description: >
          uri pointing to docker/apptainer image that should be used
        format: uri-reference
    required:
      - container

  resources_references:
    type: string
    description: >
      path to yaml file containing compute resource configuration
    format: uri-reference

  svdb_build:
    type: object
    description: >
      config for the svdb_build rule
    properties:
      container:
        type: string
        description: >
          uri pointing to docker/apptainer image that should be used
        format: uri-reference
    required:
      - container

  svdb_export:
    type: object
    description: >
      config for the svdb_export rule
    properties:
      container:
        type: string
        description: >
          uri pointing to docker/apptainer image that should be used
        format: uri-reference
    required:
      - container

required:
  - bed_to_interval_list
  - cnvkit_build_normal_reference
  - cnvkit_create_targets
  - collect_read_counts
  - create_read_count_panel_of_normals
  - default_container
  - preprocess_intervals
  - resources_references
  - svdb_build
  - svdb_export
