name: small integration test

# Controls when the action will run.
on:
   # Triggers the workflow on push or pull request events but only for the master and develop branch
  push:
    branches:
     - dev
     - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  integration-small-conda:
    name: integration small data set conda
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Add conda to system path
        run: |
          echo $CONDA/bin >> $GITHUB_PATH
      - name: Install dependencies
        run: |
          conda install -c conda-forge mamba
      - name: Install requirements.txt
        run: |
          pip install -r requirements.txt
      - name: Install requirements.test.txt
        run: |
          pip install -r requirements.test.txt
      - name: Integration test - small dataset
        working-directory: .tests/integration
        run: |
          mamba install -c conda-forge -c bioconda snakemake
          snakemake -s ../../workflow/Snakefile \
            --configfile config/config.yaml \
            -j 1 \
            --use-conda \
            --show-failed-logs
  integration-small-singularity:
    name: integration small data set singularity
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Add conda to system path
        run: |
          echo $CONDA/bin >> $GITHUB_PATH
      - name: Install dependencies
        run: |
          conda install -c conda-forge mamba
      - name: Install requirements.txt
        run: |
          pip install -r requirements.txt
      - name: Install requirements.test.txt
        run: |
          pip install -r requirements.test.txt
      - name: Install singularity
        run: |
          mamba install -c conda-forge -c bioconda singularity
      - name: Integration test - small dataset
        working-directory: .tests/integration
        run: |
          snakemake -s ../../workflow/Snakefile \
            --configfile config/config.yaml \
            -j 1 \
            --show-failed-logs \
            --use-singularity \
            --singularity-args "--cleanenv --bind /home/runner"
