name: Lint

on:
  pull_request:
    branches:
     - dev
     - main

  workflow_dispatch:

jobs:
  lint:
    name: Lint workflow
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Set up Python 3.8
        uses: actions/setup-python@v5
        with:
          python-version: 3.8
      - name: Install requirements
        run: |
          pip install -r requirements.txt
      - name: Linting
        working-directory: .tests/integration
        run: |
          snakemake -s ../../workflow/Snakefile \
            --configfile ../../config/config.yaml config/config.yaml \
            --lint
