name: Lint

# Controls when the action will run.
on:
   # Triggers the workflow on push or pull request events but only for the master and develop branch
  push:
    branches:
     - dev
     - main
  pull_request:
    branches:
     - dev
     - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  lint:
    name: Lint workflow
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Install requirements
        run: |
          pip install -r requirements.txt
      - name: Linting
        working-directory: .tests/integration
        run: |
          snakemake -s ../../workflow/Snakefile \
            --configfile ../../config/config.yaml config/config.yaml \
            --lint
