name: Lint

# Controls when the action will run.
on:
   # Triggers the workflow on push or pull request events but only for the master and develop branch
  push:
    branches:
     - dev
     - main
  pull_request:
    branches:
     - dev
     - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  lint:
    name: Lint workflow
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Miniconda setup
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.8
          auto-update-conda: true
          mamba-version: "*"
          channels: conda-forge,defaults
          channel-priority: true
      - name: Install requirements
        shell: bash -l {0}
        run: |
          pip install -r requirements.txt
          mamba install -c conda-forge -c bioconda snakemake
      - name: Linting
        shell: bash -l {0}
        working-directory: .tests/integration
        run: |
          snakemake -s ../../workflow/Snakefile \
            --configfile ../../config/config.yaml config/config.yaml \
            --lint
