name: pycodestyle

on:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches:
      - dev
      - main

  workflow_dispatch:

jobs:
  pycodestyle:
    name: pycodestyle
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.8
        uses: actions/setup-python@v5
        with:
          python-version: 3.8
      - name: Install requirements.txt
        run: |
          pip install -r requirements.txt
      - name: Install requirements.test.txt
        run: |
          pip install -r requirements.test.txt
      - name: Check python syntax lib
        run: pycodestyle --max-line-length=130 --statistics workflow/scripts
