name: Snakefmt

on:
  pull_request:
    branches:
     - dev
     - main

  workflow_dispatch:

jobs:
  snakefmt:
    name: Snakefmt
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_SNAKEMAKE_SNAKEFMT: true
          OUTPUT_FOLDER: .github/linters/report
