name: Snakemake dry run

on:
  pull_request:
    branches:
     - dev
     - main

  workflow_dispatch:

jobs:
  snakemake-dry-run:
    name: Run snakemake dry run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.8
        uses: actions/setup-python@v5
        with:
          python-version: 3.8
      - name: Install requirements.txt
        run: |
          pip install -r requirements.txt
      - name: snakemake dry run
        working-directory: .tests/integration
        run: |
          snakemake -n -s ../../workflow/Snakefile --configfile ../../config/config.yaml config/config.yaml
